---
title: "Untitled"
format: html
---

# Commandes classiques
## alias git
1 - pour voir mes alias dans mon repo
git config --local --get-regexp alias
2 - pour configurer des alias
git config --local alias.wk '!git add -u ".github/workflows/" && git commit -m "improve workflows"'
3 - git stash - ne pas oublier les fichiers untrackers
git stash push -u -m "WIP: convertisseur"
## docker
1 - lance le container
docker-compose down && docker-compose up -d
2 - jupyter
docker exec my-selenium python -m ipykernel install --name=selenium --display-name="Selenium Python"
3 - lance code
docker exec my-selenium  python  main.py
4 - get list kernels
docker exec my-selenium jupyter kernelspec list
http://localhost:8888
5 voir les images
docker image ls 
6 - supprimer les containers arretes
docker container prune

docker exec my-selenium python reminder.py local


# Voir tous les commits qui ont modifié ce fichier
git log --pretty=format:"%h %ad | %s%d [%an]" --date=short .github/workflows/clever_registration.yml


backup-main-2024-11-27

ff81d3d

git show 05b73ad:.github/workflows/clever_registration.yml > test.yml  
git stash save -u "keep" 
git stash show stash@{0}     


# Voir tous les commits qui ont modifié ce fichier
git log --oneline .github/workflows/clever_registration.yml

# Ou avec plus de détails
git log --pretty=format:"%h %ad | %s%d [%an]" --date=short .github/workflows/clever_registration.yml

# Comparer avec le commit précédent dans terminal
git diff HEAD~1 HEAD -- .github/workflows/clever_registration.yml 


# Créer des fichiers temporaires et les comparer
git show f99c9c8:.github/workflows/clever_registration.yml > /tmp/workflow-old.yml
cp .github/workflows/clever_registration.yml  /tmp/workflow-current.yml
code -d /tmp/workflow-old.yml /tmp/workflow-current.yml


# Sauver la vieille version
git show f99c9c8:.github/workflows/clever_registration.yml > ~/Desktop/workflow-f99c9c8.yml

# Ouvrir les deux dans VS Code
code ~/Desktop/workflow-f99c9c8.yml .github/workflows/bot-his.yml


FICHIER="docker-compose.yml" && git show jupyter:$FICHIER > /tmp/jupyter.txt && git show main:$FICHIER > /tmp/event.txt && /usr/local/bin/code --wait --diff /tmp/event.txt /tmp/jupyter.txt
FICHIER="github/workflows/clever_registration.yml" && git show f99c9c8:$FICHIER > /tmp/f99c9c8.yml && git show HEAD:$FICHIER > /tmp/current.yml && code --wait --diff /tmp/f99c9c8.yml /tmp/current.yml

FICHIER=".github/workflows/clever_registration.yml" && git show f99c9c8:$FICHIER > /tmp/f99c9c8.yml && git show HEAD:$FICHIER > /tmp/current.yml && code --wait --diff /tmp/f99c9c8.yml /tmp/current.yml


git show f99c9c8::.github/workflows/clever_registration.yml


git log --pretty=format:"%h %ad | %s%d [%an]" --date=short .github/actions/load-any-params/action.yml


FICHIER=".github/actions/load-any-params/action.yml" && git show 34731ae:$FICHIER > 34731ae.yml && git show HEAD:$FICHIER > current.yml && code --wait --diff /tmp/34731ae.yml /tmp/current.yml

git show f99c9c8:.github/workflows/clever_registration.yml > /tmp/workflow-old.yml

FICHIER=".github/actions/load-any-params/action.yml" && git show dd8f27c:$FICHIER > dd8f27c.yml && git show HEAD:$FICHIER > current.yml


# Voir tous les containers (même arrêtés)
docker ps -a

# Arrêter tous les containers
docker stop $(docker ps -aq)

# Nettoyer les containers arrêtés
docker container prune -f

# Relancer ton container
docker compose up