name: "count tags"
description: "Count git tags"
runs:
  using: composite
  steps:
    - name: Mark repo as safe (évite 'dubious ownership')
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Fetch tags
      run: git fetch --tags --force

    - name: Count tags
      id: count
      shell: bash
      run: |
        TAG_COUNT=$(git tag | wc -l)
        echo "tag_count=$TAG_COUNT" >> "$GITHUB_OUTPUT"