name: Reminder

permissions:
  contents: write
  actions: read


on:
  schedule:
    - cron: '0 6 * * *' # 00:00 Calgary

  workflow_dispatch:  # Ajoutez cette ligne

#limitation expect registration to begin a 6 UTC"

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      # ==========================================
      # STEP 1: Checkout code and fetch tags
      # ==========================================
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      # STEP 3: Registration attempt
      # ==========================================
      - name: Reminder
        id: reminder
        uses: devcontainers/ci@v0.3
        env:

          YOUR_SECRET_EMAIL: ${{ secrets.YOUR_SECRET_EMAIL }}
          YOUR_SECRET_PASSWORD: ${{ secrets.YOUR_SECRET_PASSWORD }}
          YOUR_SECRET_LOGON_URL: ${{ secrets.YOUR_SECRET_LOGON_URL }}
          YOUR_SECRET_PLANNING_URL: ${{ secrets.YOUR_SECRET_PLANNING_URL }}
          YOUR_SECRET_LOGIN_URL: ${{ secrets.YOUR_SECRET_LOGIN_URL }}
          YOUR_SECRET_MY_NAME: ${{ secrets.YOUR_SECRET_MY_NAME }}
          YOUR_SECRET_APPOINTMENT: ${{ secrets.YOUR_SECRET_APPOINTMENT }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

        with:
          runCmd: |
            echo "======================================"
            echo "🎾 Pickleball Reminder"
            echo "======================================"

            python3 reminder.py
          push: never

