name: Test registration Pickleball

on:
  # Automatic trigger at precise time
  schedule:
    - cron: '0 18 * * 1'  # Every Monday at 12:00 PM Calgary time
    # Calgary time: 12:00 PM Monday = 18:00 UTC Monday (MDT, UTC-6)
    # Note: GitHub Actions uses UTC, Calgary = UTC-7 (MST winter) or UTC-6 (MDT summer)
    # During summer (MDT): 12:00 PM Calgary = 18:00 UTC
    # During winter (MST): 12:00 PM Calgary = 19:00 UTC
    
  # Manual trigger with customizable parameters
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date (format: DD-MMM-YY, e.g., 19-Aug-25)'
        required: true
        default: '19-Aug-25'
        type: string
      target_time:
        description: 'Target time (format: H:MM or HH:MM, e.g., 4:30 or 14:30)'
        required: true
        default: '12:00'
        type: string

# Default values for automatic executions
env:
  DEFAULT_DATE: "19-Aug-25"
  DEFAULT_TIME: "12:00"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set parameters
        id: params
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "date=${{ github.event.inputs.target_date }}" >> $GITHUB_OUTPUT
            echo "time=${{ github.event.inputs.target_time }}" >> $GITHUB_OUTPUT
            echo "trigger_type=manual" >> $GITHUB_OUTPUT
            echo "environment=manual" >> $GITHUB_OUTPUT
          else
            echo "date=${{ env.DEFAULT_DATE }}" >> $GITHUB_OUTPUT
            echo "time=${{ env.DEFAULT_TIME }}" >> $GITHUB_OUTPUT
            echo "trigger_type=scheduled" >> $GITHUB_OUTPUT
            echo "environment=scheduled" >> $GITHUB_OUTPUT
          fi
          
      - name: Run Python test in devcontainer
        uses: devcontainers/ci@v0.3
        env:
          YOUR_SECRET_EMAIL: ${{ secrets.YOUR_SECRET_EMAIL }}
          YOUR_SECRET_PASSWORD: ${{ secrets.YOUR_SECRET_PASSWORD }}
          YOUR_SECRET_LOGON_URL: ${{ secrets.YOUR_SECRET_LOGON_URL }}
          YOUR_SECRET_PLANNING_URL: ${{ secrets.YOUR_SECRET_PLANNING_URL }}
          YOUR_SECRET_LOGIN_URL: ${{ secrets.YOUR_SECRET_LOGIN_URL }}
          YOUR_SECRET_My_NAME: ${{ secrets.YOUR_SECRET_My_NAME }}
          # Additional environment variables
          EXECUTION_ENVIRONMENT: ${{ steps.params.outputs.environment }}
          TRIGGER_TYPE: ${{ steps.params.outputs.trigger_type }}
        with:
          runCmd: python3 execution.py "${{ steps.params.outputs.date }}" "${{ steps.params.outputs.time }}"
          push: never
