name:  Test registration Pickleball
on: 
  push:
    branches: [ main]
# Déclenchement automatique à une heure précise
  schedule:
    - cron: '25 7 * * 1'  # Tous les samedis à 00:25 Calgary time (UTC-7/UTC-6)
    # Calgary time: 00:25 samedi = 07:25 UTC samedi (heure standard)
    # Note: GitHub Actions utilise UTC, Calgary = UTC-7 (hiver) ou UTC-6 (été)
  
# Déclenchement manuel avec paramètres personnalisables
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date (format: DD-MMM-YY, e.g., 19-Aug-25)'
        required: true
        default: '19-Aug-25'
        type: string
      target_time:
        description: 'Target time (format: H:MM or HH:MM, e.g., 4:30 or 14:30)'
        required: true
        default: '4:30'
        type: string
        
# Valeurs par défaut pour les exécutions automatiques
env:
  DEFAULT_DATE: "19-Aug-25"
  DEFAULT_TIME: "4:30"
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Python test in devcontainer
        uses: devcontainers/ci@v0.3
        env:
          YOUR_SECRET_EMAIL: ${{ secrets.YOUR_SECRET_EMAIL }}
          YOUR_SECRET_PASSWORD: ${{ secrets.YOUR_SECRET_PASSWORD }}
          YOUR_SECRET_LOGON_URL: ${{ secrets.YOUR_SECRET_LOGON_URL }}
          YOUR_SECRET_PLANNING_URL: ${{ secrets.YOUR_SECRET_PLANNING_URL }}
          YOUR_SECRET_LOGIN_URL: ${{ secrets.YOUR_SECRET_LOGIN_URL }}
          YOUR_SECRET_My_NAME: ${{ secrets.YOUR_SECRET_My_NAME }}         
          # Variables d'environnement supplémentaires
          EXECUTION_ENVIRONMENT: ${{ steps.params.outputs.environment }}
          TRIGGER_TYPE: ${{ steps.params.outputs.trigger_type }}

        with:
          runCmd: python3 execution.py "${{ steps.params.outputs.date }}" "${{ steps.params.outputs.time }}"
          push: never
