name: Test Python in devcontainer
on: 
  push:
    branches: [ main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      YOUR_SECRET_EMAIL: ${{ secrets.YOUR_SECRET_EMAIL }}
      YOUR_SECRET_PASSWORD: ${{ secrets.YOUR_SECRET_PASSWORD }}
      YOUR_SECRET_LOGON_URL: ${{ secrets.YOUR_SECRET_LOGON_URL }}
      YOUR_SECRET_PLANNING_URL: ${{ secrets.YOUR_SECRET_PLANNING_URL }}
      YOUR_SECRET_LOGIN_URL: ${{ secrets.YOUR_SECRET_LOGIN_URL }}
      YOUR_SECRET_My_NAME: ${{ secrets.YOUR_SECRET_My_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Python test in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            python test_import.py
          push: never