name: Test Python in devcontainer
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Python test in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            python test_import.py